In [ ]:
import os
from google.colab import drive

drive.mount('/content/drive', force_remount=True)

output_dir = '/content/drive/MyDrive/omg_diploma_2025/Diploma_Data'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

Mounted at /content/drive

In [ ]:
!pip install -q datasets pandas conllu tqdm

from datasets import load_dataset
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import json
import pandas as pd
import conllu
import requests
import numpy as np
import ast
import re
import random
import zipfile
import io
import gc

In [ ]:
# datasets ideas (for start)
# https://huggingface.co/datasets/IlyaGusev/ru_news
# https://huggingface.co/datasets/IlyaGusev/gazeta (https://arxiv.org/pdf/2006.11063)
# https://huggingface.co/datasets/RussianNLP/rucola (https://github.com/IlyaGusev/RuCoLA/tree/main) # for evaluation
# https://huggingface.co/datasets/Helsinki-NLP/opus_books
# https://huggingface.co/datasets/universal-dependencies/universal_dependencies (https://github.com/UniversalDependencies/UD_Russian-SynTagRus/tree/master)


# print("Loading Lenta.ru...")
# dataset = load_dataset("ilearning/lenta_ru_news", split="train", streaming=True)

### google drive setup

# Text cleaning

In [ ]:
MAX_WORDS_PER_CHUNK = 250
# TARGET_COUNT = 15000
WIKI_LIMIT = 200000

LABEL_MAP = {
    "O": 0, # Space only
    ".": 1,
    ",": 2,
    "!": 3,
    "?": 4,
    ":": 5,
    ";": 6,
    "-": 7,

    '"': 8,
    ' "': 9,
    '" ': 10,

    ', "': 11,
    ': "': 12,
    '. "': 13,

    '",': 14,
    '".': 15,
    '"?': 16,
    '"!': 17,
    '...': 18,

    '- "': 19,
    '", -': 20, # direct speech with closing "
    '!" -': 21,
    '?" -': 22,
    '. -': 23,

    '""': 24,      # Double close (поступил в учреждение "школа "Эврика"".)

    "! -": 25, # direct speech without closing "
    "? -": 26,
    ", -": 27,
}

ID_TO_LABEL = {v: k for k, v in LABEL_MAP.items()}

In [ ]:
for k, v in LABEL_MAP.items(): print(k, v)

O 0
. 1
, 2
! 3
? 4
: 5
; 6
- 7
" 8
 " 9
"  10
, " 11
: " 12
. " 13
", 14
". 15
"? 16
"! 17
... 18
- " 19
", - 20
!" - 21
?" - 22
. - 23
"" 24
! - 25
? - 26
, - 27

In [ ]:
# to do:
# 1. handle parentheses, brackets etc. (just return them)
# 2. minus before numbers etc (-8,5 'C)
# 3.

In [ ]:
file_path = os.path.join(output_dir, "label_map.json")
with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(ID_TO_LABEL, f, ensure_ascii=False)

In [ ]:
def robust_clean_text(text):
    text = re.sub(r'[\u2010-\u2015]', '-', text)
    text = re.sub(r'[«»“”„]', '"', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [ ]:
# def get_smart_tokens(text):
#     """
#     Tokens that should NOT be split
#     1. URLs/Emails (dots/slashes)
#     2. Numbers (integers, decimals, negatives -8,5)
#     3. Words (including words with internal hyphens like 'кто-то')
#     4. Wrappers (parentheses)
#     """
#     token_pattern = r'''
#         (?x)                        # Verbose mode
#         (?:[({[\"\']*?)             # 1. Optional Prefix: ( { [ " '
#         (?:                         # 2. Main Body (One of these):
#             https?://\S+|www\.\S+   #    A. URL (catch this first!)
#             |
#             -?\d+(?:[.,/]\d+)+      #    B. Complex Num: -8.5, 1/2, 10.000 (No spaces!)
#             |
#             -?\d+                   #    C. Simple Integer: 5, -5 (Negative sign attached)
#             |
#             [\w]+(?:-[\w]+)*        #    D. Word: word, кто-то (Hyphens inside words allowed)
#         )
#         (?:[)\]}\"\']*?)            # 3. Optional Suffix: ) ] } " '
#     '''
#     return list(re.finditer(token_pattern, text))

In [ ]:
# def normalize_gap(gap_text):
#     """
#     Converts raw gap text into a label ID key.
#     """
#     if not gap_text.strip():
#         return "O"

#     # Remove generic whitespace
#     clean = gap_text.strip()

#     # --- HANDLING YOUR SPECIFIC "BUGGED" GAPS ---

#     # Logic: Remove spaces around marks to find the skeleton
#     skeleton = re.sub(r'\s+', '', clean)

#     # Heuristics for spacing (needed for quotes)
#     has_leading_space = gap_text.startswith(' ')

#     # 1. Simple Marks
#     if skeleton in ['.', ',', '!', '?', ':', ';', '-']:
#         return skeleton

#     # 2. Quotes (Context Aware)
#     if skeleton == '"':
#         return ' "' if has_leading_space else '" '

#     # 3. Complex Clusters (Skeleton matching)
#     mapping = {
#         ',"' : ', "',  ':"' : ': "',  '."' : '. "',
#         '",' : '",',   '".' : '".',   '"?' : '"?',   '"!' : '"!',
#         '-"' : '- "',  '",-' : '", -',
#         '!-' : '! -',  '?-' : '? -',  '.-' : '. -',  ',-' : ', -',
#         '""' : '""',   '"" ' : '"" ', '"",' : '"",'
#     }

#     return mapping.get(skeleton, "O") # Default to O if unknown mess

In [ ]:
# def extract_labels_standardized(text):
#     text = robust_clean_text(text)

#     # Use the Smart Tokenizer
#     matches = get_smart_tokens(text)

#     result_pairs = []

#     for i, match in enumerate(matches):
#         word = match.group() # The token (including brackets/negatives)
#         start_pos = match.end()

#         # Find the gap until the next token starts
#         if i + 1 < len(matches):
#             end_pos = matches[i+1].start()
#             gap_text = text[start_pos:end_pos]
#         else:
#             # End of sentence case (usually ignored or treated as final mark)
#             # For BERT training, we usually drop the very last mark or treat it as padding,
#             # but let's capture it.
#             gap_text = text[start_pos:]

#         # Determine Label
#         label_key = normalize_gap(gap_text)
#         label_id = LABEL_MAP.get(label_key, 0)

#         result_pairs.append({"word": word, "label": label_id})

#     return result_pairs

In [ ]:
def get_canonical_label(gap_text):
    if not gap_text.strip():
        return "O"

    # capture spacing before stripping to distinguishes ' "' from '" '
    has_leading_space = gap_text.startswith(' ')
    # assume standard punctuation implies trailing space for simple marks
    # but for quotes it's different
    skeleton = re.sub(r'\s+', '', gap_text)

    if skeleton == '.': return '.'
    if skeleton == ',': return ','
    if skeleton == '!': return '!'
    if skeleton == '?': return '?'
    if skeleton == ':': return ':'
    if skeleton == ';': return ';'
    if skeleton == '-': return '-'

    if skeleton == '"':
        # If leading space => Open Quote
        if has_leading_space:
            return ' "'
        # otherwise assume Close Quote
        return '" '

    if skeleton == ',"': return ', "'
    if skeleton == ':"': return ': "'
    if skeleton == '."': return '. "'

    if skeleton == '",': return '",'
    if skeleton == '".': return '".'
    if skeleton == '"?': return '"?'
    if skeleton == '"!': return '"!'

    if skeleton == '-"': return '- "'
    if skeleton == '",-': return '", -'
    if skeleton == '!"-': return '!"-'
    if skeleton == '?"-': return '?"-'

    if skeleton == '!-': return '! -'
    if skeleton == '?-': return '? -'
    if skeleton == '.-': return '. -'
    if skeleton == ',-': return ', -'

    if skeleton == '""': return '""' # Fallback
    if skeleton == '"",': return '"",'

    return "O"

In [ ]:

def extract_labels_standardized(text):
    text = robust_clean_text(text)

    # number:
    # -?              : Optional negative
    # \d+             : digit start
    # (?:[.,]\d+)+    : followed by a group of (dot OR comma) + digits, repeated 1+ times
    # punct doesn't divide parts of number
    number_pattern = r"-?\d+(?:[.,]\d+)+"

    # word:
    # -?           -> optional minus (in numbers like -1.5)
    # [(\[]?       -> Optional ( or [
    # [\w]+        -> word characters
    # (?:-[\w]+)*  -> Optional hyphen
    # [)\]]?       -> Optional closing ) or ]
    word_pattern = r"-?[(\[]?[\w]+(?:-[\w]+)*[)\]]?"

    # standalone brackets
    brackets_pattern = r"[()]|[\[\]]"

    full_pattern = f"{number_pattern}|{word_pattern}|{brackets_pattern}"

    word_iter = list(re.finditer(full_pattern, text))

    result_pairs = []

    for i, match in enumerate(word_iter):
        word = match.group()
        start_gap = match.end()

        if i + 1 < len(word_iter):
            end_gap = word_iter[i+1].start()
            raw_gap = text[start_gap:end_gap]
        else:
            raw_gap = text[start_gap:]

        label_str = get_canonical_label(raw_gap)
        label_id = LABEL_MAP.get(label_str, 0)

        result_pairs.append({"word": word, "label": label_id})

    return result_pairs

In [ ]:
def create_json_dataset(texts, output_filename):
    processed_data = []
    print(f"Processing {len(texts)} texts for {output_filename}...")

    for i, text in enumerate(tqdm(texts)):
        try:
            pairs = extract_labels_standardized(text)
        except:
            continue

        if len(pairs) < 5: continue # Skip tiny fragments

        tokens = [p['word'] for p in pairs]
        ner_tags = [p['label'] for p in pairs]

        processed_data.append({
            "tokens": tokens,
            "ner_tags": ner_tags
        })

    full_path = os.path.join(output_dir, output_filename)

    with open(full_path, 'w', encoding='utf-8') as f:
        json.dump(processed_data, f, ensure_ascii=False)

    del processed_data
    gc.collect()

    print(f"Saved {full_path}")

In [ ]:
def fix_wiki_encoding(text):
    if not isinstance(text, str):
        # If bytes, decode it
        try:
            text = text.decode('utf-8')
        except:
            pass
    if text.startswith("b'") or text.startswith('b"'):
        try:
            # literal_eval turns "b'\xd0\xb0'" (str) -> b'\xd0\xb0' (bytes)
            # then .decode('utf-8') turns bytes -> "а" (str)
            text = ast.literal_eval(text).decode('utf-8')
        except (ValueError, SyntaxError):
            pass

    tags_to_remove = [
        "_START_ARTICLE_",
        "_START_SECTION_",
        # "_START_PARAGRAPH_",
        # "_NEWLINE_"
    ]

    for tag in tags_to_remove:
        text = text.replace(tag, " ")

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

# Syntagrus preparation

In [ ]:
# URLs for training
syntagrus_urls = [
    "https://raw.githubusercontent.com/UniversalDependencies/UD_Russian-SynTagRus/master/ru_syntagrus-ud-train-a.conllu",
    "https://raw.githubusercontent.com/UniversalDependencies/UD_Russian-SynTagRus/master/ru_syntagrus-ud-train-b.conllu",
    "https://raw.githubusercontent.com/UniversalDependencies/UD_Russian-SynTagRus/master/ru_syntagrus-ud-train-c.conllu"
]

In [ ]:
def process_syntagrus_files(urls, dataset_name):
    chunks = []
    print(f"--- PROCESSING {dataset_name} ---")
    for url in urls:
        fname = url.split("/")[-1]
        if not os.path.exists(fname):
            r = requests.get(url)
            with open(fname, "wb") as f: f.write(r.content)

        current_chunk = []
        current_word_count = 0
        current_doc_id = None
        current_genre = None

        with open(fname, "r", encoding="utf-8") as f:
            for sentence in tqdm(conllu.parse_incr(f)):
                sent_id = sentence.metadata['sent_id']
                text = sentence.metadata['text']
                genre = sentence.metadata.get('genre', 'unknown')
                doc_id = sent_id.rsplit("_", 1)[0] if "_" in sent_id else sent_id

                if doc_id != current_doc_id:
                    if current_chunk:
                        chunks.append({"text": " ".join(current_chunk), "genre": current_genre})
                    current_chunk = []
                    current_word_count = 0
                    current_doc_id = doc_id
                    current_genre = genre
                elif current_genre == 'unknown' and genre != 'unknown':
                    current_genre = genre

                sent_len = len(text.split())
                if current_chunk and (current_word_count + sent_len > MAX_WORDS_PER_CHUNK):
                    chunks.append({"text": " ".join(current_chunk), "genre": current_genre})
                    current_chunk = []
                    current_word_count = 0
                current_chunk.append(text)

        if current_chunk:
            chunks.append({"text": " ".join(current_chunk), "genre": current_genre})
    return pd.DataFrame(chunks)

In [ ]:
df_syn = process_syntagrus_files(syntagrus_urls, "SynTagRus TRAIN")

--- PROCESSING SynTagRus TRAIN ---

24516it [00:22, 1112.92it/s]
24299it [00:12, 1929.71it/s]
20816it [00:10, 2044.00it/s]

# Gazeta load

In [ ]:
ext_journalism = []
gazeta_url = "https://huggingface.co/datasets/IlyaGusev/gazeta/resolve/main/gazeta_train.jsonl"

response = requests.get(gazeta_url, stream=True)
total_size = int(response.headers.get('content-length', 0))
line_count = 0
# target_count = 15000

for line in tqdm(response.iter_lines(), desc="Gazeta Lines"): # , total=target_count
    # if line_count >= target_count:
    #     break
    if line:
        try:
            data = json.loads(line)
            # 'text' is the article body
            t = data['text'].replace('\n', ' ')
            if len(t) > 100:
                ext_journalism.append(t)
                line_count += 1
        except:
            continue

print(f"Loaded {len(ext_journalism)} Gazeta samples.")

Gazeta Lines: 1it [00:00, 3675.99it/s]

Loaded 0 Gazeta samples.

# Helsinki Opus books

In [ ]:
# from oxen import RemoteRepo
# repo = RemoteRepo("Helsinki-NLP/opus_books")
# repo.download("en-ru/opus_books_en-ru_train.parquet", revision="main")

# import pandas as pd
# df = pd.read_parquet("https://hub.oxen.ai/api/repos/Helsinki-NLP/opus_books/file/main/en-ru/opus_books_en-ru_train.parquet")
# print(df.head())

# "https://opus.nlpl.eu/Books/ru&en/v1/Books#download"

In [ ]:
# import nltk
# nltk.download('punkt')
from nltk.tokenize import sent_tokenize

def chunk_external_text(text, max_words=MAX_WORDS_PER_CHUNK):
    sentences = sent_tokenize(text, language='russian')
    chunks = []
    current_chunk_sentences = []
    current_word_count = 0

    for sentence in sentences:
        sentence_words = sentence.split()
        sentence_len = len(sentence_words)

        if current_chunk_sentences and (current_word_count + sentence_len > max_words):
            chunks.append(" ".join(current_chunk_sentences))
            current_chunk_sentences = [sentence]
            current_word_count = sentence_len
        else:
            current_chunk_sentences.append(sentence)
            current_word_count += sentence_len

    if current_chunk_sentences:
        chunks.append(" ".join(current_chunk_sentences))

    return chunks

In [ ]:
ext_fiction = []
opus_url = "https://object.pouta.csc.fi/OPUS-Books/v1/moses/en-ru.txt.zip"

response = requests.get(opus_url, stream=True)
total_size = int(response.headers.get('content-length', 0))

with io.BytesIO() as buffer:
    for chunk in response.iter_content(chunk_size=4096): buffer.write(chunk)
    print("Unzipping...")
    with zipfile.ZipFile(buffer) as z:
        with z.open('Books.en-ru.ru') as f:
            for line in tqdm(f, desc="Opus Stream"):
                try:
                    t = line.decode('utf-8').strip()
                    if len(t) > 20:
                        chunks = chunk_external_text(t)
                        ext_fiction.extend(chunks)
                except: continue
print(f"Loaded {len(ext_fiction)} Opus chunks.")

Unzipping...

Opus Stream: 17496it [00:13, 1310.12it/s]

Loaded 0 Opus chunks.

# Wikipedia

In [ ]:
def check_heading_punctuation(heading_text):
    if not heading_text:
        return False
    pairs = extract_labels_standardized(heading_text)
    if not pairs:
        return False

    last_word_label = pairs[-1]['label']
    return last_word_label != LABEL_MAP["O"]

In [ ]:
import re
import ast

def parse_wiki_segments(raw_item_text):
    text_content = ""
    if not isinstance(raw_item_text, str):
        try:
            text_content = raw_item_text.decode('utf-8')
        except (UnicodeDecodeError, AttributeError):
            try:
                text_content = ast.literal_eval(raw_item_text).decode('utf-8')
            except (ValueError, SyntaxError, AttributeError):
                return []
    else:
        text_content = raw_item_text

    text_content = text_content.replace('_NEWLINE_', ' ')
    text_content = re.sub(r'\s+', ' ', text_content).strip()

    tag_definitions = {
        "_START_ARTICLE_": "article_heading",
        "_START_SECTION_": "section_heading",
        "_START_PARAGRAPH_": "paragraph"
    }

    tag_pattern = '|'.join(re.escape(tag) for tag in tag_definitions.keys())

    segments = []
    last_end = 0

    first_match = re.search(tag_pattern, text_content)
    if first_match:
        pre_tag_text = text_content[0:first_match.start()]
        cleaned_pre_tag_text = robust_clean_text(pre_tag_text)
        if cleaned_pre_tag_text:
            segments.append({"text": cleaned_pre_tag_text, "type": "paragraph"})

    for match in re.finditer(tag_pattern, text_content):
        tag = match.group(0)
        start_index = match.end()

        next_match = re.search(tag_pattern, text_content[start_index:])
        if next_match:
            end_index = start_index + next_match.start()
        else:
            end_index = len(text_content)

        segment_text = text_content[start_index:end_index]
        cleaned_segment_text = robust_clean_text(segment_text)

        if cleaned_segment_text:
            segment_type = tag_definitions.get(tag, "unknown")

            if segment_type in ["article_heading", "section_heading"]:
                if not check_heading_punctuation(cleaned_segment_text):
                    continue

            segments.append({"text": cleaned_segment_text, "type": segment_type})

        last_end = end_index

    if last_end < len(text_content):
        remaining_text = text_content[last_end:]
        cleaned_remaining_text = robust_clean_text(remaining_text)
        if cleaned_remaining_text:
            segments.append({"text": cleaned_remaining_text, "type": "paragraph"})

    return segments

In [ ]:
# ext_science = []
# ds_wiki = load_dataset("wiki40b", "ru", split="train", streaming=True)
# count = 0
# target_count = WIKI_LIMIT

# for item in tqdm(ds_wiki, total=target_count, desc="Wiki Stream"):
#     if count >= target_count: break

#     raw_text = item['text']
#     clean_text = fix_wiki_encoding(raw_text)
#     if len(clean_text) > 100 and "_START_" not in clean_text:
#         ext_science.append(clean_text)
#         count += 1

# print(f"Loaded {len(ext_science)} clean Wiki samples.")
# if len(ext_science) > 0:
#     print("Sample check:", ext_science[0][:100])

In [ ]:
ext_science = []
ds_wiki = load_dataset("wiki40b", "ru", split="train", streaming=True)
count = 0
target_count = WIKI_LIMIT

for item in tqdm(ds_wiki, total=target_count, desc="Wiki Stream"):
    if count >= target_count: break

    raw_text = item['text']
    # Use fix_wiki_encoding first to handle the raw text.
    cleaned_full_text = fix_wiki_encoding(raw_text)

    # Then parse into segments
    segments = parse_wiki_segments(cleaned_full_text)

    for segment in segments:
        text = segment['text']
        # Filter for length and append
        if len(text) > 100:
            ext_science.append(text)
            count += 1
            if count >= target_count: # Check limit after each append
                break

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Resolving data files:   0%|          | 0/29 [00:00<?, ?it/s]

Wiki Stream:  47%|████▋     | 94129/200000 [02:12<02:29, 708.88it/s]

# Merging datasets (by genres)

In [ ]:
# get Syntagrus genre tag
def get_syn_texts(genres):
    return df_syn[df_syn['genre'].isin(genres)]['text'].tolist()

In [ ]:
journ_texts = get_syn_texts(['journalism', 'news', 'publicistic']) + ext_journalism
print(f"Domain 'Journalism': {len(journ_texts)} samples")

fiction_texts = get_syn_texts(['fiction', 'literature']) + ext_fiction
print(f"Domain 'Fiction':    {len(fiction_texts)} samples")

science_texts = get_syn_texts(['nonfiction', 'wiki', 'science']) + ext_science
print(f"Domain 'Science':    {len(science_texts)} samples")

Domain 'Journalism': 53 samples
Domain 'Fiction':    17 samples
Domain 'Science':    200023 samples

# Generating jsons by genres

In [ ]:
domains = {
    "journalism": journ_texts,
    "fiction": fiction_texts,
    "science": science_texts
}

all_train_texts = []
all_test_texts = []

for domain_name, texts in domains.items():
    train_txt, test_txt = train_test_split(texts, test_size=0.1, random_state=42)

    create_json_dataset(train_txt, f"train_{domain_name}.json")
    create_json_dataset(test_txt, f"test_{domain_name}.json")

    all_train_texts.extend(train_txt)
    all_test_texts.extend(test_txt)

Processing 47 texts for train_journalism.json...

100%|██████████| 47/47 [00:00<00:00, 158.76it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/train_journalism.json
Processing 6 texts for test_journalism.json...

100%|██████████| 6/6 [00:00<00:00, 178.65it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/test_journalism.json
Processing 15 texts for train_fiction.json...

100%|██████████| 15/15 [00:00<00:00, 80.42it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/train_fiction.json
Processing 2 texts for test_fiction.json...

100%|██████████| 2/2 [00:00<00:00, 117.89it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/test_fiction.json
Processing 180020 texts for train_science.json...

100%|██████████| 180020/180020 [01:38<00:00, 1834.12it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/train_science.json
Processing 20003 texts for test_science.json...

100%|██████████| 20003/20003 [00:11<00:00, 1704.57it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/test_science.json

In [ ]:
import random
random.shuffle(all_train_texts)

print("\nProcessing Combined 'ALL' Dataset...")
create_json_dataset(all_train_texts, "train_all.json")
create_json_dataset(all_test_texts, "test_all.json")

print("\nDONE!datasets ready for BERT:")
print("1. train/test_all.json        (Generalist Model)")
print("2. train/test_journalism.json (Specialist Experiment)")
print("3. train/test_fiction.json    (Specialist Experiment)")
print("4. train/test_science.json    (Specialist Experiment)")

Processing Combined 'ALL' Dataset...
Processing 180082 texts for train_all.json...

100%|██████████| 180082/180082 [01:29<00:00, 2005.86it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/train_all.json
Processing 20011 texts for test_all.json...

100%|██████████| 20011/20011 [00:12<00:00, 1607.51it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/test_all.json

DONE!datasets ready for BERT:
1. train/test_all.json        (Generalist Model)
2. train/test_journalism.json (Specialist Experiment)
3. train/test_fiction.json    (Specialist Experiment)
4. train/test_science.json    (Specialist Experiment)

# Testing data

In [ ]:
syntagrus_test_url = ["https://raw.githubusercontent.com/UniversalDependencies/UD_Russian-SynTagRus/master/ru_syntagrus-ud-test.conllu"]
df_syn_test = process_syntagrus_files(syntagrus_test_url, "SynTagRus TEST")

--- PROCESSING SynTagRus TEST ---

8800it [00:04, 1802.32it/s]

## *domains testing*

In [ ]:
def get_texts_by_genre(df, genres):
    return df[df['genre'].isin(genres)]['text'].tolist()

print("\n--- ASSEMBLING FINAL DATASETS ---")

domains = {
    "journalism": {
        "syn_keywords": ['journalism', 'news', 'publicistic'],
        "external": ext_journalism
    },
    "fiction": {
        "syn_keywords": ['fiction', 'literature'],
        "external": ext_fiction
    },
    "science": {
        "syn_keywords": ['nonfiction', 'wiki', 'science'],
        "external": ext_science
    }
}

--- ASSEMBLING FINAL DATASETS ---

In [ ]:
all_train_texts = []

for domain_name, sources in domains.items():
    syn_train_txt = get_texts_by_genre(df_syn, sources['syn_keywords'])
    domain_train = syn_train_txt + sources['external']

    create_json_dataset(domain_train, f"train_{domain_name}.json")
    all_train_texts.extend(domain_train)

    bench_test_txt = get_texts_by_genre(df_syn_test, sources['syn_keywords'])

    if len(bench_test_txt) == 0:
        print(f"No test data found for {domain_name} in SynTagRus Test!")
    else:
        create_json_dataset(bench_test_txt, f"bench_test_{domain_name}.json")

Processing 53 texts for train_journalism.json...

100%|██████████| 53/53 [00:00<00:00, 134.89it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/train_journalism.json
Processing 4 texts for bench_test_journalism.json...

100%|██████████| 4/4 [00:00<00:00, 172.26it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/bench_test_journalism.json
Processing 17 texts for train_fiction.json...

100%|██████████| 17/17 [00:00<00:00, 62.41it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/train_fiction.json
Processing 3 texts for bench_test_fiction.json...

100%|██████████| 3/3 [00:00<00:00, 73.01it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/bench_test_fiction.json
Processing 200023 texts for train_science.json...

100%|██████████| 200023/200023 [01:35<00:00, 2084.11it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/train_science.json
Processing 3 texts for bench_test_science.json...

100%|██████████| 3/3 [00:00<00:00, 51.84it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/bench_test_science.json

## *merged domain training & testing*

In [ ]:
random.shuffle(all_train_texts)

# Create Validation Set (Just 5% of training data to check convergence)
train_txt, val_txt = train_test_split(all_train_texts, test_size=0.05, random_state=42)

print("\nProcessing Generalist Datasets...")
create_json_dataset(train_txt, "train_all.json")
create_json_dataset(val_txt, "val_internal.json")

print("\nDONE! Dataset Manifest:")
print("1. train_all.json         -> Main Training Data (Gazeta+Opus+Wiki+SynTagRusTrain)")
print("2. val_internal.json      -> For checking loss during training")
print("3. train_[genre].json     -> For Domain Adaptation Training")
print("4. bench_test_[genre].json -> OFFICIAL BENCHMARK (SynTagRus Test Only)")

Processing Generalist Datasets...
Processing 190088 texts for train_all.json...

100%|██████████| 190088/190088 [01:44<00:00, 1811.54it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/train_all.json
Processing 10005 texts for val_internal.json...

100%|██████████| 10005/10005 [00:03<00:00, 2680.31it/s]

Saved /content/drive/MyDrive/omg_diploma_2025/Diploma_Data/val_internal.json

DONE! Dataset Manifest:
1. train_all.json         -> Main Training Data (Gazeta+Opus+Wiki+SynTagRusTrain)
2. val_internal.json      -> For checking loss during training
3. train_[genre].json     -> For Domain Adaptation Training
4. bench_test_[genre].json -> OFFICIAL BENCHMARK (SynTagRus Test Only)

## Visuzlization

In [ ]:
data_files = {
    "train": os.path.join(output_dir, "train_all.json"),
    "validation": os.path.join(output_dir, "val_internal.json")
}
raw_datasets = load_dataset("json", data_files=data_files, streaming=True)

In [ ]:
import pandas as pd

def visualize_dataset(dataset_split, num_samples=5, id2label=ID_TO_LABEL):
    samples = []
    # Iterate over the streaming dataset to collect samples
    for i, example in enumerate(dataset_split):
        if i >= num_samples:
            break
        samples.append(example)

    # If no samples were collected (e.g., empty dataset or num_samples=0)
    if not samples:
        return pd.DataFrame()

    df = pd.DataFrame(samples)
    if id2label:
        def get_label_names(tag_ids):
            return [id2label[int(t)] for t in tag_ids]

        df['ner_tags_names'] = df['ner_tags'].apply(get_label_names)
        cols = ['tokens', 'ner_tags_names', 'ner_tags'] + [c for c in df.columns if c not in ['tokens', 'ner_tags_names', 'ner_tags']]
        df = df[cols]
    pd.set_option('display.max_colwidth', None)

    return df

df_view = visualize_dataset(raw_datasets['train'], num_samples=3, id2label=ID_TO_LABEL)

display(df_view)

,tokens,ner_tags_names,ner_tags
0,"[Гетероду, плекс, гибридный, участок, молекул, ДНК, вступивших, в, рекомбинацию, состоящий, из, двух, цепей, от, каждой, из, рекомбинирующих, ДНК, (то, есть, разного, происхождения), Одиночные, цепи, удерживаются, друг, с, другом, благодаря, водородным, связям, между, комплементарными, основаниями, Участки, в, которых, основания, не, подходят, друг, другу, приобретают, форму, петли, Чем, больше, в, гетеродуплексе, неспаренных, участков, тем, менее, он, устойчив, поэтому, может, осуществляться, подгонка, оснований, друг, под, друга, В, некоторых, случаях, гетеродуплекс, могут, образовывать, одиночные, цепи, РНК, Чтобы, определить, содержит, ли, ДНК, интроны, можно, провести, её, транскрипцию, с, последующей, гибридизацией, полученной, цепи, РНК, с, матрицей, исходной, ДНК, Если, ДНК, содержит, интроны, то, в, транскрибированной, с, ...]","[O, -, O, O, O, ,, O, O, ,, O, O, O, O, O, O, O, O, O, O, O, O, ., O, O, O, O, O, O, O, O, O, O, O, ., ,, O, O, O, O, O, O, ,, O, O, ., O, O, O, O, O, ,, O, O, O, ,, O, O, O, O, O, O, O, ., O, O, O, O, O, O, O, O, ., O, ,, O, O, O, ,, O, O, O, O, O, O, O, O, O, O, O, -, O, ., O, O, O, ,, O, O, O, O, ...]","[0, 7, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, ...]"
1,"[Родился, 23, декабря, 1923, года, в, армянской, семье, в, городе, Ленинакан, (ныне, г, Гюмри, Армения), ССР, Армении, в, многодетной, семье, плотника, вагонного, депо, на, железной, дороге, Апета, Аматуни, Назван, был, Ашотом, в, честь, друга, отца, рано, ушедшего, из, жизни, В, семье, помимо, него, было, ещё, 11, детей, каждого, из, которых, отец, приучил, к, ответственности, и, труду, позже, Ашот, Аматуни, говорил, что, именно, благодаря, этим, чертам, привитым, отцом, он, с, отличием, окончил, школу, и, поступил, в, Ленинаканский, педагогический, институт, С, 1930, по, 1940, годы, учился, в, 51-й, железнодорожной, средней, школе, Ленинакана, Семья]","[O, O, O, O, O, O, O, O, O, O, O, O, ., ,, O, O, O, O, O, O, O, O, O, O, O, O, O, ., O, O, O, O, O, O, ,, O, O, O, ., O, O, O, O, O, O, O, ,, O, O, O, O, O, O, O, O, ,, O, O, O, ,, O, O, O, O, ,, O, ,, O, O, O, O, O, O, O, O, O, O, ., O, O, O, O, O, O, O, O, O, O, O, ., O]","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]"
2,"[Окончил, филологический, факультет, Новгородского, государственного, университета, получив, специальность, учителя, литературы, В, 2002, году, опубликован, сборник, стихотворений, Бударагина, Звёзды, в, квадрате, окна, В, октябре, 2003, года, принял, участие, в, Третьем, форуме, молодых, писателей, России, (мастер-класс, Кирилла, Ковальджи), Как, литератор, публиковался, в, калининградском, журнале, Насекомое, До, 2007-го, года, работал, главным, редактором, официального, сайта, партии, Единая, Россия, был, членом, Федерального, политсовета, Молодой, гвардии, Единой, России, Писал, материалы, для, многих, изданий, Известия, (на, сайте, Известий, размещены, его, материалы, за, 2006-2008, годы), Русский, Журнал, (размещены, его, публикации, за, 2005-2008, годы), GlobalRus, ru, (размещены, его, статьи, за, 2005-2007, годы), а, также, региональных, изданий, Основатель, Новгородского, политического, ...]","[O, O, O, O, O, ,, O, O, O, ., O, O, O, O, O, O, "", O, O, O, ""., O, O, O, O, O, O, O, O, O, O, O, O, O, O, ., O, ,, O, O, O, "", ""., O, O, O, O, O, O, O, O, "", O, "",, O, O, O, "", O, O, O, ""., O, O, O, O, - "", "" , O, "", "" , O, O, O, O, O, , "", O, "" , O, O, O, O, O, , "", ., "" , O, O, O, O, O, ,, O, O, O, ., "", O, O, ...]","[0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 9, 15, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 14, 0, 0, 0, 9, 0, 0, 0, 15, 0, 0, 0, 0, 19, 10, 0, 9, 10, 0, 0, 0, 0, 0, 11, 0, 10, 0, 0, 0, 0, 0, 11, 1, 10, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 9, 0, 0, ...]"

In [ ]:
def audit_example(dataset_split, index, id2label):
    example = dataset_split[index]
    tokens = example['tokens']
    tags = example['ner_tags']

    data = []
    for t, tag_id in zip(tokens, tags):
        data.append({
            "Token": t,
            "Tag ID": tag_id,
            "Label": id2label[int(tag_id)]
        })

    return pd.DataFrame(data)

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None)

def audit_example_from_dict(example_dict, id2label):
    """
    Audits a single example given as a dictionary.
    """
    tokens = example_dict['tokens']
    tags = example_dict['ner_tags']

    data = []
    for t, tag_id in zip(tokens, tags):
        data.append({
            "Token": t,
            "Tag ID": tag_id,
            "Label": id2label[int(tag_id)]
        })
    return pd.DataFrame(data)

def audit_multiple_examples(dataset_split, indices, id2label):
    collected_examples = {}
    max_index = max(indices) if indices else -1

    for i, example in enumerate(dataset_split):
        if i > max_index and len(collected_examples) == len(indices):
            break
        if i in indices:
            collected_examples[i] = example

    for idx in indices:
        if idx in collected_examples:
            print(f"\n example index = {idx}")
            df = audit_example_from_dict(collected_examples[idx], id2label)
            display(df)
        else:
            print(f"\n Example at index {idx} not found. Dataset might be smaller than requested index or not enough items were streamed.")

audit_multiple_examples(raw_datasets['train'], [0, 1, 2, 100], ID_TO_LABEL)

 example index = 0

                  Token  Tag ID Label
0              Гетероду       0     O
1                 плекс       7     -
2             гибридный       0     O
3               участок       0     O
4               молекул       0     O
5                   ДНК       2     ,
6            вступивших       0     O
7                     в       0     O
8          рекомбинацию       2     ,
9             состоящий       0     O
10                   из       0     O
11                 двух       0     O
12                цепей       0     O
13                   от       0     O
14               каждой       0     O
15                   из       0     O
16      рекомбинирующих       0     O
17                  ДНК       0     O
18                  (то       0     O
19                 есть       0     O
20              разного       0     O
21       происхождения)       1     .
22            Одиночные       0     O
23                 цепи       0     O
24         удерживаются       0     O
25                 друг       0     O
26                    с       0     O
27               другом       0     O
28            благодаря       0     O
29           водородным       0     O
30               связям       0     O
31                между       0     O
32     комплементарными       0     O
33          основаниями       1     .
34              Участки       2     ,
35                    в       0     O
36              которых       0     O
37            основания       0     O
38                   не       0     O
39             подходят       0     O
40                 друг       0     O
41                другу       2     ,
42          приобретают       0     O
43                форму       0     O
44                петли       1     .
45                  Чем       0     O
46               больше       0     O
47                    в       0     O
48       гетеродуплексе       0     O
49          неспаренных       0     O
50             участков       2     ,
51                  тем       0     O
52                менее       0     O
53                   он       0     O
54             устойчив       2     ,
55              поэтому       0     O
56                может       0     O
57       осуществляться       0     O
58             подгонка       0     O
59            оснований       0     O
60                 друг       0     O
61                  под       0     O
62                друга       1     .
63                    В       0     O
64            некоторых       0     O
65              случаях       0     O
66        гетеродуплекс       0     O
67                могут       0     O
68         образовывать       0     O
69            одиночные       0     O
70                 цепи       0     O
71                  РНК       1     .
72                Чтобы       0     O
73           определить       2     ,
74             содержит       0     O
75                   ли       0     O
76                  ДНК       0     O
77              интроны       2     ,
78                можно       0     O
79             провести       0     O
80                   её       0     O
81         транскрипцию       0     O
82                    с       0     O
83          последующей       0     O
84        гибридизацией       0     O
85           полученной       0     O
86                 цепи       0     O
87                  РНК       0     O
88                    с       0     O
89             матрицей       7     -
90             исходной       0     O
91                  ДНК       1     .
92                 Если       0     O
93                  ДНК       0     O
94             содержит       0     O
95              интроны       2     ,
96                   то       0     O
97                    в       0     O
98   транскрибированной       0     O
99                    с       0     O
100                 неё       0     O
101                 РНК       0     O
102               после       0     O
103        транскрипции       0     O
104                   и       0     O
105        последующего       0     O
106          сплайсинга       0     O
107                 они       0     O
108            окажутся       0     O
109          удалёнными       1     .
110               Из-за       0     O
111               этого       0     O
112                 при       0     O
113        гибридизации       0     O
114                 РНК       0     O
115                   с       0     O
116         материнской       0     O
117                 ДНК       0     O
118            появятся       0     O
119         петлевидные       0     O
120             участки       0     O
121         неспаренных       0     O
122           оснований       2     ,
123                 так       0     O
124                 как       0     O
125            интронам       0     O
126                   в       0     O
127                 ДНК       0     O
128                 нет       0     O
129     соответствующих       0     O
130           оснований       0     O
131                   в       0     O
132                 РНК       1     .

 example index = 1

              Token  Tag ID Label
0           Родился       0     O
1                23       0     O
2           декабря       0     O
3              1923       0     O
4              года       0     O
5                 в       0     O
6         армянской       0     O
7             семье       0     O
8                 в       0     O
9            городе       0     O
10        Ленинакан       0     O
11            (ныне       0     O
12                г       1     .
13            Гюмри       2     ,
14         Армения)       0     O
15              ССР       0     O
16          Армении       0     O
17                в       0     O
18      многодетной       0     O
19            семье       0     O
20         плотника       0     O
21        вагонного       0     O
22             депо       0     O
23               на       0     O
24         железной       0     O
25           дороге       0     O
26            Апета       0     O
27          Аматуни       1     .
28           Назван       0     O
29              был       0     O
30           Ашотом       0     O
31                в       0     O
32            честь       0     O
33            друга       0     O
34             отца       2     ,
35             рано       0     O
36         ушедшего       0     O
37               из       0     O
38            жизни       1     .
39                В       0     O
40            семье       0     O
41           помимо       0     O
42             него       0     O
43             было       0     O
44              ещё       0     O
45               11       0     O
46            детей       2     ,
47          каждого       0     O
48               из       0     O
49          которых       0     O
50             отец       0     O
51          приучил       0     O
52                к       0     O
53  ответственности       0     O
54                и       0     O
55            труду       2     ,
56            позже       0     O
57             Ашот       0     O
58          Аматуни       0     O
59          говорил       2     ,
60              что       0     O
61           именно       0     O
62        благодаря       0     O
63             этим       0     O
64           чертам       2     ,
65         привитым       0     O
66            отцом       2     ,
67               он       0     O
68                с       0     O
69         отличием       0     O
70          окончил       0     O
71            школу       0     O
72                и       0     O
73         поступил       0     O
74                в       0     O
75    Ленинаканский       0     O
76   педагогический       0     O
77         институт       1     .
78                С       0     O
79             1930       0     O
80               по       0     O
81             1940       0     O
82             годы       0     O
83           учился       0     O
84                в       0     O
85             51-й       0     O
86  железнодорожной       0     O
87          средней       0     O
88            школе       0     O
89       Ленинакана       1     .
90            Семья       0     O

 example index = 2

                 Token  Tag ID Label
0              Окончил       0     O
1       филологический       0     O
2            факультет       0     O
3        Новгородского       0     O
4     государственного       0     O
5         университета       2     ,
6              получив       0     O
7        специальность       0     O
8              учителя       0     O
9           литературы       1     .
10                   В       0     O
11                2002       0     O
12                году       0     O
13         опубликован       0     O
14             сборник       0     O
15       стихотворений       0     O
16          Бударагина       9     "
17              Звёзды       0     O
18                   в       0     O
19            квадрате       0     O
20                окна      15    ".
21                   В       0     O
22             октябре       0     O
23                2003       0     O
24                года       0     O
25              принял       0     O
26             участие       0     O
27                   в       0     O
28             Третьем       0     O
29              форуме       0     O
30             молодых       0     O
31           писателей       0     O
32              России       0     O
33       (мастер-класс       0     O
34             Кирилла       0     O
35          Ковальджи)       1     .
36                 Как       0     O
37           литератор       2     ,
38        публиковался       0     O
39                   в       0     O
40     калининградском       0     O
41             журнале       9     "
42           Насекомое      15    ".
43                  До       0     O
44             2007-го       0     O
45                года       0     O
46             работал       0     O
47             главным       0     O
48          редактором       0     O
49        официального       0     O
50               сайта       0     O
51              партии       9     "
52              Единая       0     O
53              Россия      14    ",
54                 был       0     O
55              членом       0     O
56        Федерального       0     O
57         политсовета       9     "
58             Молодой       0     O
59             гвардии       0     O
60              Единой       0     O
61              России      15    ".
62               Писал       0     O
63           материалы       0     O
64                 для       0     O
65              многих       0     O
66             изданий      19   - "
67            Известия      10    "
68                 (на       0     O
69               сайте       9     "
70            Известий      10    "
71           размещены       0     O
72                 его       0     O
73           материалы       0     O
74                  за       0     O
75           2006-2008       0     O
76               годы)      11   , "
77             Русский       0     O
78              Журнал      10    "
79          (размещены       0     O
80                 его       0     O
81          публикации       0     O
82                  за       0     O
83           2005-2008       0     O
84               годы)      11   , "
85           GlobalRus       1     .
86                  ru      10    "
87          (размещены       0     O
88                 его       0     O
89              статьи       0     O
90                  за       0     O
91           2005-2007       0     O
92               годы)       2     ,
93                   а       0     O
94               также       0     O
95        региональных       0     O
96             изданий       1     .
97          Основатель       9     "
98       Новгородского       0     O
99       политического       0     O
100              клуба      15    ".
101                Был       0     O
102         редактором       0     O
103            раздела       9     "
104          Авторские       0     O
105            колонки      10    "
106                  и       0     O
107             отдела       0     O
108           политики       0     O
109                  в       0     O
110    Интернет-газете       9     "
111             ВЗГЛЯД       1     .
112                 РУ      14    ",
113                где       0     O
114             сейчас       0     O
115              ведёт       0     O
116          авторскую       0     O
117            колонку       1     .
118             Вместе       0     O
119                  с       0     O
120            Андреем       0     O
121          Маруденко       0     O
122          Бударагин       0     O
123             открыл       0     O
124     информационный       0     O
125             портал       9     "
126       Новгородские       0     O
127            Хроники      10    "
128                  о       0     O
129          Новгороде       0     O
130                  и       0     O
131      Северо-Западе       0     O
132             России       2     ,
133            который       0     O
134              позже       0     O
135               стал       0     O
136     общероссийским       0     O
137  Интернет-изданием       9     "
138              Новые       0     O
139            Хроники      14    ",
140                где       0     O
141                 до       0     O
142                сих       0     O
143                пор       0     O
144          размещены       0     O
145          материалы       0     O
146            Михаила       2     ,
147       датированные       0     O
148          2007-2008       0     O
149             годами       1     .
150                Две       0     O
151             статьи       0     O
152            Михаила       0     O
153                (за       0     O
154               2005       0     O
155                  и       0     O
156               2007       0     O
157               год)       0     O
158       опубликованы       0     O
159                  в       0     O
160            издании       9     "
161          Агентство       0     O
162       политических       0     O
163           новостей      15    ".
164         Участвовал       0     O
165                 во       0     O
166      Всероссийском       0     O
167           конкурсе       0     O
168            молодых       0     O
169        журналистов       0     O
170                  и       0     O
171                уже       0     O
172              тогда       2     ,
173                  в       0     O
174               2006       0     O
175               году       2     ,
176        опубликовал       0     O
177             статью       0     O
178                  в       9     "
179          Известиях      15    ".
180              Ведёт       0     O
181              Живой       0     O
182             Журнал       0     O
183                  и       9     "
184            Твиттер      10    "
185                под       0     O
186              ником       0     O
187         joe_malaba       1     .
188        Воспитывает       0     O
189               сына       1     .
190    Коллекционирует       0     O
191              нэцкэ       1     .

 example index = 100

           Token  Tag ID Label
0              В       0     O
1        декабре       0     O
2           2017       0     O
3     российские       0     O
4              и       0     O
5      сирийские       0     O
6            СМИ       0     O
7       сообщили       2     ,
8            что       0     O
9              в       0     O
10         Сирии       0     O
11          ЗРПК       9     "
12    Панцирь-С1      10    "
13          сбил       9     "
14          Лору      14    ",
15    запущенную       0     O
16      Израилем       0     O
17            по       0     O
18     сирийской       0     O
19       военной       0     O
20          базе       0     O
21             в       0     O
22        городе       0     O
23     Аль-Кисва       1     .
24  Комментариев       0     O
25   израильских       0     O
26           СМИ       0     O
27           или       0     O
28  министерства       0     O
29       обороны       0     O
30            не       0     O
31   последовало       1     .